[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "senamhi-query"
version = "0.1.0"
description = "Consulta de estaciones SENAMHI desde Python"
readme = "README.md"
authors = [
  { name="Michael De La Cruz" }
]
dependencies = [
  "requests"
]
